# Generated by Django 4.0.2 on 2022-02-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputImage', models.ImageField(upload_to='')),
                ('outputMask', models.ImageField(blank=True, null=True, upload_to='')),
                ('outputImage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
